INSERT INTO mla_list (name, party, constituency, district, lok_sabha_seat) VALUES
('Rabiram Narzary', 'BPF', 'Dotma (ST)', 'Kokrajhar', 'Kokrajhar'),
('Rupam Chandra Roy', 'BPF', 'Baokhungri', 'Kokrajhar', 'Kokrajhar'),
('Md Ashraful Islam Sheikh', 'INC', 'Parbatjhora', 'Kokrajhar', 'Kokrajhar'),
('Ashwini Roy Sarkar', 'BJP', 'Golakganj', 'Dhubri', 'Dhubri'),
('Abdus Sobahan Ali Sarkar', 'INC', 'Gauripur', 'Dhubri', 'Dhubri'),
('Wazed Ali Choudhury', 'INC', 'Birsing Jarua', 'Dhubri', 'Dhubri'),
('Jibesh Rai', 'AGP', 'Bilasipara', 'Dhubri', 'Dhubri'),
('Mohibur Rohman', 'INC', 'Mankachar', 'South Salmara-Mankachar', 'Dhubri'),
('Aftab Uddin Mollah', 'INC', 'Jaleshwar', 'Goalpara', 'Dhubri'),
('Pabitra Rabha', 'BJP', 'Goalpara West (ST)', 'Goalpara', 'Guwahati'),
('Abul Kalam Rasheed Alam', 'INC', 'Goalpara East', 'Goalpara', 'Dhubri'),
('Tankeswar Rabha', 'BJP', 'Dudhnai (ST)', 'Goalpara', 'Guwahati'),
('Bhupen Roy', 'BJP', 'Abhayapuri', 'Bongaigaon', 'Barpeta'),
('Md. Nurul Islam', 'INC', 'Srijangram', 'Bongaigaon', 'Dhubri'),
('Diptimayee Choudhury', 'AGP', 'Bongaigaon', 'Bongaigaon', 'Barpeta'),
('Paniram Brahma', 'BPF', 'Sidli–Chirang (ST)', 'Chirang', 'Kokrajhar'),
('Arup Kumar Dey', 'BJP', 'Bijni', 'Chirang', 'Kokrajhar'),
('Ranjeet Kumar Dass', 'BJP', 'Bhowanipur–Sorbhog', 'Bajali', 'Barpeta'),
('Abdur Rahim Ahmed', 'INC', 'Chenga', 'Barpeta', 'Dhubri'),
('Dipak Kumar Das', 'AGP', 'Barpeta (SC)', 'Barpeta', 'Barpeta'),
('Jakir Hussain Sikdar', 'INC', 'Pakabetbari', 'Barpeta', 'Barpeta'),
('Dharmeswar Roy', 'AGP', 'Bajali', 'Bajali', 'Barpeta'),
('Rekibuddin Ahmed', 'INC', 'Chamaria', 'Kamrup', 'Guwahati'),
('Raju Mesh', 'BJP', 'Boko–Chaygaon (ST)', 'Kamrup', 'Guwahati'),
('Himangshu Shekhar Baishya', 'BJP', 'Palasbari', 'Kamrup', 'Guwahati'),
('Prakash Chandra Das', 'AGP', 'Hajo–Sualkuchi (SC)', 'Kamrup', 'Barpeta'),
('Bhabesh Kalita', 'BJP', 'Rangiya', 'Kamrup', 'Darrang-Udalguri'),
('Diganta Kalita', 'BJP', 'Kamalpur', 'Kamrup', 'Darrang-Udalguri'),
('Narayan Deka', 'BJP', 'Barkhetri', 'Nalbari', 'Barpeta'),
('Jayanta Malla Baruah', 'BJP', 'Nalbari', 'Nalbari', 'Barpeta'),
('Chandra Mohan Patowary', 'BJP', 'Tihu', 'Nalbari', 'Barpeta'),
('Thaneswar Basumatary', 'BPF', 'Manas', 'Baksa', 'Kokrajhar'),
('Maneswar Brahma', 'BPF', 'Baksa (ST)', 'Baksa', 'Kokrajhar'),
('Biswajit Daimary', 'BJP', 'Tamulpur (ST)', 'Tamulpur', 'Darrang-Udalguri'),
('Victor Kumar Das', 'BJP', 'Goreshwar', 'Tamulpur', 'Darrang-Udalguri'),
('Maheswar Baro', 'BPF', 'Bhergaon', 'Udalguri', 'Darrang-Udalguri'),
('Rihon Daimary', 'BPF', 'Udalguri (ST)', 'Udalguri', 'Darrang-Udalguri'),
('Charan Boro', 'BPF', 'Majbat', 'Udalguri', 'Darrang-Udalguri'),
('Bikan Chandra Deka', 'BJP', 'Tangla', 'Udalguri', 'Darrang-Udalguri'),
('Paramananda Rajbongshi', 'BJP', 'Sipajhar', 'Darrang', 'Darrang-Udalguri'),
('Nilima Devi', 'BJP', 'Mangaldai', 'Darrang', 'Darrang-Udalguri'),
('Mazibur Rahman', 'AIUDF', 'Dalgaon', 'Darrang', 'Darrang-Udalguri'),
('Asif Mohammad Nazar', 'INC', 'Laharighat', 'Morigaon', 'Nagaon'),
('Mehboob Mukhtar', 'RD', 'Dhing', 'Nagaon', 'Nagaon'),
('Nurul Huda', 'INC', 'Rupohihat', 'Nagaon', 'Nagaon'),
('Keshab Mahanta', 'AGP', 'Kaliabor', 'Nagaon', 'Kaziranga'),
('Mohammed Badruddin Ajmal', 'AIUDF', 'Binnakandi', 'Hojai', 'Kaziranga'),
('Shiladitya Dev', 'BJP', 'Hojai', 'Hojai', 'Kaziranga'),
('Sibu Misra', 'BJP', 'Lumding', 'Hojai', 'Kaziranga'),
('Ritu Baran Sarmah', 'BJP', 'Barchalla', 'Sonitpur', 'Sonitpur'),
('Prithiraj Rava', 'AGP', 'Tezpur', 'Sonitpur', 'Sonitpur'),
('Krishna Kamal Tanti', 'BJP', 'Rangapara', 'Sonitpur', 'Sonitpur'),
('Pallab Lochan Das', 'BJP', 'Biswanath', 'Biswanath', 'Sonitpur'),
('Munindra Das', 'BJP', 'Behali (SC)', 'Biswanath', 'Sonitpur'),
('Utpal Borah', 'BJP', 'Gohpur', 'Biswanath', 'Sonitpur'),
('Rishiraj Hazarika', 'BJP', 'Rongonadi', 'Lakhimpur', 'Lakhimpur'),
('Joy Prakash Das', 'INC', 'Naoboicha (SC)', 'Lakhimpur', 'Lakhimpur'),
('Naba Kumar Doley', 'BJP', 'Dhakuakhana (ST)', 'Lakhimpur', 'Lakhimpur'),
('Ranoj Pegu', 'BJP', 'Dhemaji (ST)', 'Dhemaji', 'Lakhimpur'),
('Jiban Gogoi', 'BJP', 'Sissiborgaon', 'Dhemaji', 'Lakhimpur'),
('Bhubon Pegu', 'BJP', 'Jonai (ST)', 'Dhemaji', 'Lakhimpur'),
('Bolin Chetia', 'BJP', 'Sadiya', 'Tinsukia', 'Lakhimpur'),
('Suren Phukan', 'BJP', 'Digboi', 'Tinsukia', 'Dibrugarh'),
('Sanjoy Kishan', 'BJP', 'Makum', 'Tinsukia', 'Dibrugarh'),
('Chakradhar Gogoi', 'BJP', 'Khowang', 'Dibrugarh', 'Dibrugarh'),
('Taranga Gogoi', 'BJP', 'Naharkatia', 'Dibrugarh', 'Dibrugarh'),
('Bhuban Gam', 'BJP', 'Majuli (ST)', 'Majuli', 'Jorhat'),
('Ajanta Neog', 'BJP', 'Golaghat', 'Golaghat', 'Kaziranga'),
('Mridul Kumar Dutta', 'BJP', 'Dergaon', 'Golaghat', 'Kaziranga'),
('Mrinal Saikia', 'BJP', 'Khumtai', 'Golaghat', 'Kaziranga'),
('Biswajit Phukan', 'BJP', 'Sarupathar', 'Golaghat', 'Kaziranga'),
('Surjya Rongphar', 'BJP', 'Bokajan (ST)', 'Karbi Anglong', 'Diphu'),
('Lunsing Teron', 'BJP', 'Howraghat (ST)', 'Karbi Anglong', 'Diphu'),
('Niso Terangpi', 'BJP', 'Diphu (ST)', 'Karbi Anglong', 'Diphu'),
('Tuliram Ronghang', 'BJP', 'Rongkhang (ST)', 'West Karbi Anglong', 'Diphu'),
('Habbey Teron', 'BJP', 'Amri (ST)', 'West Karbi Anglong', 'Diphu'),
('Rupali Langthasa', 'BJP', 'Haflong (ST)', 'Dima Hasao', 'Diphu'),
('Kaushik Rai', 'BJP', 'Lakhipur', 'Cachar', 'Silchar'),
('Rajdeep Goala', 'BJP', 'Udharbond', 'Cachar', 'Silchar'),
('Kamalakhya Dey Purkayastha', 'BJP', 'Katigorah', 'Cachar', 'Silchar'),
('Kishor Nath', 'BJP', 'Borkhola', 'Cachar', 'Silchar'),
('Dr. Rajdeep Roy', 'BJP', 'Silchar', 'Cachar', 'Silchar'),
('Amiya Kanti Das', 'BJP', 'Dholai (SC)', 'Cachar', 'Silchar'),
('Milon Das', 'BJP', 'Hailakandi', 'Hailakandi', 'Karimganj'),
('Zubair Anam Mazumder', 'INC', 'Algapur-Katlicherra', 'Hailakandi', 'Karimganj'),
('Krishnendu Paul', 'BJP', 'Patharkandi', 'Sribhumi', 'Karimganj'),
('Bijoy Malakar', 'BJP', 'Ram Krishna Nagar (SC)', 'Sribhumi', 'Karimganj'),
('Susanta Borgohain', 'BJP', 'Demow', 'Sibsagar', 'Jorhat'),
('Nazirul Hussain', 'INC', 'Nazira', 'Sibsagar', 'Jorhat'),
('Akhil Gogoi', 'RJRD', 'Sibsagar', 'Sibsagar', 'Jorhat'),
('Atul Bora', 'AGP', 'Bokakhat', 'Golaghat', 'Kaziranga')
ON CONFLICT (constituency) DO UPDATE 
SET lok_sabha_seat = EXCLUDED.lok_sabha_seat,
    name = EXCLUDED.name,
    party = EXCLUDED.party,
    district = EXCLUDED.district;

